### ISSUE TITLE
operator =- do not work

### ISSUE THREAD

**Issue by elucian** [koi-lang/design#5]
Operator =- can't work if you also use  -x as unary operator.  x=-1 will produce x==-1 that is not x=x-1

**Comment by DeflatedPickle** [comment]
If anything, it would produce `x = -1`. But it's likely that the lexer will understand what you want unless you're not using spaces, which only a madman would do.

**Comment by elucian** [comment]
spaces are usually insignificant in compilers. if you do not enforce a rule that is not a rule.
