### ISSUE TITLE
elf vs elif

### ISSUE THREAD

**Issue by elucian** [koi-lang/design#6]
I suggest you rename _elf_ to _elif_  that is 2 abbreviations for two words: else if combined into one. _elif_

**Comment by DeflatedPickle** [comment]
But the word "elf" is fun... Plus it means that `if`/`elf`/`else` blocks are structured like stairs, 2 then 3 then 4.

**Comment by elucian** [comment]
yes is fun but do not have significance. many developers are using elif in Python so is easy to learn. If you wish to design a bad language that is impossible to learn then you can create a language that have no keywords and is using only spaces. So nobody will be able to read it.
